# UR10e Reach Analysis Configuration

# Wall position
wall:
  x_position: 1.2  # meters

# Workspace analysis parameters
workspace:
  # Analysis boundary (in meters)
  y_range: [-1.0, 1.0]    # Expanded horizontal range
  z_range: [0.2, 2.2]     # Expanded vertical range
  resolution: 0.05        # Finer grid resolution for analysis
  
# Trajectory parameters
trajectory:
  num_passes: 18          # Number of horizontal passes in S-pattern (increased for finer coverage)
  point_spacing: 0.01     # Spacing between trajectory points (meters) - reduced for higher density
  
# Robot parameters
robot:
  # IK parameters
  max_ik_attempts: 15
  ik_tolerance: 0.05
  # Perpendicularity constraint
  perp_angle_threshold: 0.15  # radians (about 8.6 degrees) - stricter perpendicularity
  
# Visualization parameters
visualization:
  trajectory_speed: 0.015  # Seconds between trajectory points (increased for more controlled motion)

# Motion planning parameters
motion_planning:
  spline_density: 4          # Points per waypoint (density of trajectory)
  velocity_limit: 3.0        # Maximum joint velocity (rad/s) - increased from 0.8
  acceleration_limit: 6.0    # Maximum joint acceleration (rad/s²) - increased from 1.5
  check_collisions: false    # Whether to check for collisions during motion planning
  rrt_timeout: 1.0           # Timeout for RRT planning (seconds)
  max_iterations: 500        # Maximum iterations for RRT planning

# PID controller parameters for smooth motion
pid_controller:
  kp: 0.8                # Proportional gain (lower for smoother motion)
  ki: 0.05               # Integral gain (lower to reduce oscillation)
  kd: 0.15               # Derivative gain (higher for better damping)
  dt: 0.01               # Time step between updates (seconds)
  steps: 10              # Number of interpolation steps between waypoints

# ... existing code ... 